---
  - name: Clone jwt_tool repository
    become: true
    git:
      repo: https://github.com/ticarpi/jwt_tool
      dest: /opt/jwt_tool
      force: yes
      recursive: no
    
  - name: Install required Python packages
    pip:
      name:
        - termcolor
        - cprint
        - pycryptodomex
        - requests
      state: present
        
  - name: Make jwt_tool executable
    become: true
    ansible.builtin.file:
      path: /opt/jwt_tool/jwt_tool.py
      mode: '+x'
    delegate_to: localhost

  - name: Create symbolic link to cloned repository
    become: true
    file:
      src: /opt/jwt_tool/jwt_tool.py
      dest: //usr/bin/jwt_tool
      state: link
      force: yes
     
